include $(SUBDIR)../config.mak

NAME = avutil

HEADERS = audioconvert.h                                                \
          avstring.h                                                    \
          base64.h                                                      \
          common.h                                                      \
          crc.h                                                         \
          eval.h                                                        \
          imgutils.h                                                    \
          intfloat_readwrite.h                                          \
          lfg.h                                                         \
          log.h                                                         \
          mathematics.h                                                 \
          md5.h                                                         \
          mem.h                                                         \
          opt.h                                                         \
          parseutils.h                                                  \
          pixdesc.h                                                     \
          pixfmt.h                                                      \
          random_seed.h                                                 \
          rational.h                                                    \
          samplefmt.h                                                   \
          sha.h                                                         \

BUILT_HEADERS = avconfig.h

OBJS = audioconvert.o                                                   \
       avstring.o                                                       \
       base64.o                                                         \
       crc.o                                                            \
       des.o                                                            \
       eval.o                                                           \
       imgutils.o                                                       \
       intfloat_readwrite.o                                             \
       lfg.o                                                            \
       log.o                                                            \
       mathematics.o                                                    \
       md5.o                                                            \
       mem.o                                                            \
       opt.o                                                            \
       parseutils.o                                                     \
       pixdesc.o                                                        \
       random_seed.o                                                    \
       rational.o                                                       \
       rc4.o                                                            \
       samplefmt.o                                                      \
       sha.o                                                            \

include $(SUBDIR)../subdir.mak
