#####################################################################################
#
#   Copyright (c) 2009, Freescale Semiconductors Inc.,
#   All Rights Reserved.
# 
#   The following programs are the sole property of Freescale Semiconductors Inc.,
#   and contain its proprietary and confidential information.
# 
####################################################################################### 
#
#   This file will build whole OMX project.
#
######################################################################################


all: 
	$(MAKE) -C linux 

clean:
	$(MAKE) clean -C linux 





